#!/bin/bash
# =============================================================================
# OVMS start script — launched by supervisord after orchestrator writes sentinel
#
# Reads the OVMS config generated by the orchestrator and starts the server
# with the correct arguments.
# =============================================================================

set -euo pipefail

OVMS_CONFIG_PATH="${INIM_OVMS_CONFIG_PATH:-/tmp/ovms_config.json}"
OVMS_REST_PORT="${INIM_OVMS_PORT:-8001}"
OVMS_GRPC_PORT="${INIM_OVMS_GRPC_PORT:-8002}"
OVMS_LOG_LEVEL="${OVMS_LOG_LEVEL:-INFO}"

echo "Starting OVMS..."
echo "  Config:    ${OVMS_CONFIG_PATH}"
echo "  REST Port: ${OVMS_REST_PORT}"
echo "  gRPC Port: ${OVMS_GRPC_PORT}"
echo "  Log Level: ${OVMS_LOG_LEVEL}"

# Wait for config file to exist
MAX_WAIT=60
WAITED=0
while [ ! -f "$OVMS_CONFIG_PATH" ]; do
    if [ $WAITED -ge $MAX_WAIT ]; then
        echo "ERROR: OVMS config not found at ${OVMS_CONFIG_PATH} after ${MAX_WAIT}s"
        exit 1
    fi
    sleep 1
    WAITED=$((WAITED + 1))
done

# Launch OVMS
exec /ovms/bin/ovms \
    --config_path "${OVMS_CONFIG_PATH}" \
    --rest_port "${OVMS_REST_PORT}" \
    --grpc_port "${OVMS_GRPC_PORT}" \
    --rest_bind_address "127.0.0.1" \
    --grpc_bind_address "127.0.0.1" \
    --log_level "${OVMS_LOG_LEVEL}" \
    --file_system_poll_wait_seconds 0
